version: "3.2"
services:
  database:
    container_name: cafe_db
    image: mariadb
    volumes:
      - /volume1/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - /volume1/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - /volume1/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MYSQL_DATABASE=medicafe
      - MYSQL_ROOT_PASSWORD=medicafe!@34
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306

  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://cafe_db:3306/medicafe?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: medicafe!@34
    ports:
      - 8081:8080
    depends_on:
      - cafe_db
